== Application Service Event Recovery

{company-short-name} will develop a status page to provide real time
update and inform our customers of the status of each service. The
status page is updated with details about an event that may cause
service interruption / downtime.

A follow up root-cause analysis details (RCA) will be available to
customers upon request after the event has transpired for further
details to cause and remediation plan for the future. Event Service
Level

=== Short (hours)

* Experience a short delay in service.
* {company-short-name} will monitor the event and determine course of
action. Escalation may be required.

=== Moderate (days)

* Experience a modest delay in service where processes in flight may
need to be restarted.
* {company-short-name} will monitor the event and determine course of
action. Escalation may be required.
* {company-short-name} will notify customers of delay in service and
provide updates on {company-short-name}’s status page.

=== Long (a week or more)

* Experience a delay in service and processes in flight may need to be
restarted.
* {company-short-name} will monitor the event and determine course of
action. Escalation may be required.
* {company-short-name} will notify customers of delay in service and
provide updates on {company-short-name}’s status page.

include::ROOT:partial$footer.adoc[]