= Policy Management

`2020.1`

{company-short-name} implements policies and procedures to maintain compliance and integrity of data.
The Security Officer and Privacy Officer are responsible for maintaining policies and procedures and assuring all {company-short-name} workforce members, business associates, customers, and partners are adherent to all applicable policies.
Previous versions of policies are retained to assure ease of finding policies at specific historic dates in time.

== Policy Statements

{company-short-name} policy requires that:

(a) {company-short-name} policies must be developed and maintained to meet all applicable compliance requirements adhere to security best practices, including but not limited to:

* HIPAA
* SOC 2

(b) All policies must be reviewed at least annually.

(c) All policy changes must be approved by {company-short-name} Security Officer.
Additionally,

* Major changes may require approval by {company-short-name} CEO or designee;
* Changes to policies and procedures related to product development may require approval by the Head of Engineering.

(d) All policy documents must be maintained with version control, and previous versions must be retained for a minimum of seven years.

(e) Policy exceptions are handled on a case-by-case basis.

* All exceptions must be fully documented with business purpose and reasons why the policy requirement cannot be met.
* All policy exceptions must be approved by both {company-short-name} Security Officer and COO.
* An exception must have an expiration date no longer than one year from date of exception approval and it must be reviewed and re-evaluated on or before the expiration date.

== Controls and Procedures

=== Policy Management Process

==== Document Structure

Policies are written in individual documents, each pertaining to a specific domain of concern.

Each document starts with the current version number in the format of `YYYY.#` (e.g.
`2017.1`), followed by a brief summary.
The remaining of the document is structured to contain the following subsections:

* Policy Statements
* Applicable Standards
* Controls and Procedures

==== Versioning

Each {company-short-name} policy document contains a version and optionally a revision number.
The version number is the four digit year followed by a number, to indicate the year and sequence number of the policy at which time it was written or updated.

The version number shall be incremented by one with each material change to the policy content.
For example, if a new policy statement is added or a technical control/procedure is updated to `2017.1` version of a policy, the new version should be numbered `2017.2`.

The policy document may also include a revision number, in the format of `rev.#`, immediately following the main version number.
A revision number indicate minor, non-material changes to the document, such as formatting changes, fixing typos, or adding minor details.

==== Numbering

If sequencing numbers are included in the policy headings:

* Policy may be referenced by its statement number, such as `ยง2.1(a)`, in internal/external communications as well as in other {company-short-name} policies or technical/business documentation for cross reference.
* As such, to maintain cross referencing integrity, starting from version `2017.2`, all numbering shall remain intact for policy documents and statements.
* When updating, avoid reordering and renumbering of policy documents and statements.
For example:
 ** Append at the end of the list by adding new statement(s) as needed instead of inserting.
 ** If a policy or policy statement is no longer applicable, mark it deprecated instead of removing the file or statement completely.

==== Review and Maintenance of Policies

. All policies are stored and up to date to maintain {company-short-name} compliance with HIPAA,
+
SOC 2 and other relevant standards.
Updates and version control are done similar to source code control.

. Policy update requests can be made by any workforce member at any time.
Furthermore, all policies are reviewed annually by the Security and Privacy Officer to assure they are accurate and up-to-date.
. {company-short-name} employees may request changes to policies using the following process:
 .. The {company-short-name} employee initiates a policy change request by creating an Issue in the {ticketing-system} Security project.
The change request may optionally include a  pull request from a separate branch or repository containing the desired changes.
 .. The Security Officer or the Privacy Officer is assigned to review the policy change request.
 .. Once the review is completed, the Security Officer approves or rejects the Issue.
If the Issue is rejected, it goes back for further review and documentation.
 .. If the review is approved, the Security Officer then marks the Issue as Done, adding any pertinent notes required.
 .. If the policy change requires technical modifications to production systems, those changes are carried out by authorized personnel using {company-short-name}'s xref:ccm.adoc[change management process].
 .. If the change results in a new version instead of a new revision (see ยง3.3.1 for definitions), the current version of the policy document(s) must be saved to archive under the corresponding version number prior to the new policy being adopted/published and prior to merging the pull request containing the changes.
This allows easy reference to previous versions if necessary.

+
!!!
important
+
....
 * Changes are made on the `drafts` (or equivalent) branch instead of on the `master` branch for commits.
 * If multiple authors are working on the changes, additional separate branches and pull requests may be necessary before changes are merged in `drafts`.
 * Changes must not be merged to `master` without the approval of Security and Privacy Officer.
 * Changes must not be merged to `master` without archiving the existing version of policy document(s), unless the change is a minor revision.
 * Once the changes are final and approved, a pull request shall be created from the `drafts` branch to the `master` branch and all members of the development team shall be included as approvers.  This serves as communication and training of policy updates to the development organization, and the pull request approvals serve as records of training received.
 * Policy update communication and training for non-development staff is conducted separately by the Security team.
....
. All policies are made accessible to all {company-short-name} workforce members.
The current master policies are published at {domain-security-url}.
 ** Changes are automatically communicated to all {company-short-name} team members through integrations between  and Slack that log changes to a predefined {company-short-name} Slack Channel.
 ** The Security Officer also communicates policy changes to all employees via email.
These emails include a high-level description of the policy change using terminology appropriate for the target audience.
. All policies, and associated documentation, are retained for 7 years from the date of its creation or the date when it last was in effect, whichever is later
 .. Version history of all {company-short-name} policies is done via .
 .. Backup storage of all policies is done with AWS S3 and/or internal file share (e.g.
Microsoft Office365 SharePoint or Box).
. The policies and information security policies are reviewed and audited annually, or after significant changes occur to {company-short-name}'s organizational environment, by the security committee members.
Issues that come up as part of this process are reviewed by {company-short-name} management to assure all risks and potential gaps are mitigated and/or fully addressed.
The process for reviewing polices is outlined below:
 .. The Security Officer initiates the policy review by creating an Issue in the {ticketing-system} Security project or via a Pull Request (PR).
 .. The Security Committee members and additional reviewers are notified by email or via the PR to review the current policies.
 .. If changes are made, the above process is used.
All changes are documented in the Issue/PR.
 .. Once the review is completed, the Security Officer approves or rejects the Issue/PR.
If the Issue/PR is rejected, it goes back for further review and documentation.
 .. If the review is approved, the Security Officer then marks the Issue as Done, or merges the PR into master branch, adding any pertinent notes required.
 .. Policy review is monitored using {ticketing-system} or  reporting to assess compliance with above policy.

Additional documentation related to maintenance of policies is outlined in xref:rar.adoc[Roles and Responsibilities].

include::ROOT:partial$footer.adoc[]